### PR TITLE
Prepare for 0.1.12 release

### PR DESCRIPTION
**Pull request by kevmoo**
[Review on Reviewable](https://reviewable.io/reviews/duse-io/dart-coveralls/31)

### CODE REVIEW

**Comment by Adracus** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- CHANGELOG.md @ r1
- lib/src/cli_client.dart @ r1
- lib/src/git_data.dart @ r1
- pubspec.yaml @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/duse-io/dart-coveralls/31)

**Comment by kevmoo** [comment]
@Adracus and published as 0.1.12 :smile:

**Comment by Adracus** [comment]
@kevmoo nice :+1:

**Comment by kevmoo** [comment]
@Adracus once this CL is in, we should see a lot fewer crashes, too.

https://github.com/dart-lang/coverage/pull/74

**Comment by Adracus** [comment]
That'd be great :+1: . I'll add the travis token detection support now.

**Pull request merged**
