### PR TITLE
Upload only option, without running a script

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @kevmoo

**Comment by sethladd** [comment]
Hi. Any thoughts on this one?

**Comment by kevmoo** [comment]
Please rebase and flatten the commit.
Change the pubspec to be v 0.4.0-dev (since you changed APIs)
Please change the title of the commit to be descriptive
Please update the changelog

:smiley:

**Comment by kevmoo** [comment]
...also: run `dartfmt`

**Comment by sethladd** [comment]
sgtm thanks!

**Comment by sethladd** [comment]
ok @kevmoo I have wrangled the gits

**Comment by kevmoo** [comment]
Closed with 5cca0eadfb3f376d14d6ecffab3c4e79b8cdfa68

...and some tweaks :smile:

**Pull request closed without merging**
